server:
  port: 8003
  servlet:
    context-path: /serie/

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id]}:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

message: hello from serie-service

management:
  endpoints:
    web:
      exposure:
        include: '*'
        
spring:
  application:
    name: serie-service
  data:
    mongodb:
      database: digitalHouse
    port:
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

queue:
  serie:
    name: serieQueue

